kind: Deployment
apiVersion: apps/v1
metadata:
  name: blog-project-deployment
  namespace: nginx
  labels:
    app: blog-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-project
  template:
    metadata:
      name: blog-project-pod
      labels:
        app: blog-project
    spec:
      containers:
      - name: blog-project-container
        image: neeraj01/blog-project-k8s:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret #Didn't commid the secret.yaml file to the repository.
              key: MONGODB_URI